#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12
#bspc config active_border_color "#ffffff"
#bspc config normal_border_color "#a486dd"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Wallpaper

feh --bg-fill ~/wallpapers/wall-02.png


# Startup, clipboard & error fixes

~/.config/polybar/./launch.sh &

~/.local/bin/./eww -c ~/.config/eww/bar/ open bar

dunst &

vmware-user &

picom &
