
format = """
[╭──](fg:#4AC6FF) 󰋑  $username$directory $git_branch$git_status
[╰──](fg:#4AC6FF)$character"""

command_timeout = 5001
add_newline = true

[os]
format = "[$symbol](bold fg:blue)"
disabled = false

[os.symbols]
Windows = " "
Kali = "󰋑 "

[username]
style_user = "fg:#ffffff bold bg:#4AC6FF bold"
style_root = "#ffffff bold"
format = "[](bold fg:#4AC6FF)[$user]($style)[ ](bold fg:#4AC6FF)"
disabled = false
show_always = true

[directory]
style = "bg:#1F1F1F fg:#ffffff"
format = ' [](bold fg:#1F1F1F)[󰉋 $path]($style)[](bold fg:#1F1F1F)'

[character]
success_symbol = "[](bold fg:#4AC6FF)"
error_symbol = "[](bold fg:red)"

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 13
truncation_symbol = ""
format = "[](bold fg:#2B82CF)[$symbol $branch(:$remote_branch)](fg:#ffffff bg:#2B82CF)[ ](bold fg:#2B82CF)"
