
format = """
[╭──](fg:#A182FF)   $username$directory $git_branch$git_status
[╰──](fg:#A182FF)$character"""

command_timeout = 5001
add_newline = true

[os]
format = "[$symbol](bold fg:blue)"
disabled = false

[os.symbols]
Windows = " "
Kali = " "

[username]
style_user = "fg:#ffffff bold bg:#A182FF bold"
style_root = "#ffffff bold"
format = "[](bold fg:#A182FF)[$user]($style)[ ](bold fg:#A182FF)"
disabled = false
show_always = true

[directory]
style = "bg:#1F1F1F fg:#ffffff"
format = ' [](bold fg:#1F1F1F)[󰉋 $path]($style)[](bold fg:#1F1F1F)'

[character]
success_symbol = "[](bold fg:#A182FF)"
error_symbol = "[](bold fg:red)"

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 13
truncation_symbol = ""
format = "[](bold fg:#622EFF)[$symbol $branch(:$remote_branch)](fg:#ffffff bg:#622EFF)[ ](bold fg:#622EFF)"
